// Code generated by controller generator. DO NOT EDIT.

package service

import (
	"github.com/gin-gonic/gin"
	"github.com/boss-net/api/boss-plugin/internal/core/plugin_daemon"
	"github.com/boss-net/api/boss-plugin/internal/core/plugin_daemon/access_types"
	"github.com/boss-net/api/boss-plugin/internal/core/session_manager"
	"github.com/boss-net/api/boss-plugin/internal/utils/stream"
	"github.com/boss-net/api/boss-plugin/pkg/entities/oauth_entities"
	"github.com/boss-net/api/boss-plugin/pkg/entities/plugin_entities"
	"github.com/boss-net/api/boss-plugin/pkg/entities/requests"
)

func GetAuthorizationURL(
	r *plugin_entities.InvokePluginRequest[requests.RequestOAuthGetAuthorizationURL],
	ctx *gin.Context,
	max_timeout_seconds int,
) {
	baseSSEWithSession(
		func(session *session_manager.Session) (*stream.Stream[oauth_entities.OAuthGetAuthorizationURLResult], error) {
			return plugin_daemon.GetAuthorizationURL(session, &r.Data)
		},
		access_types.PLUGIN_ACCESS_TYPE_OAUTH,
		access_types.PLUGIN_ACCESS_ACTION_GET_AUTHORIZATION_URL,
		r,
		ctx,
		max_timeout_seconds,
	)
}

func GetCredentials(
	r *plugin_entities.InvokePluginRequest[requests.RequestOAuthGetCredentials],
	ctx *gin.Context,
	max_timeout_seconds int,
) {
	baseSSEWithSession(
		func(session *session_manager.Session) (*stream.Stream[oauth_entities.OAuthGetCredentialsResult], error) {
			return plugin_daemon.GetCredentials(session, &r.Data)
		},
		access_types.PLUGIN_ACCESS_TYPE_OAUTH,
		access_types.PLUGIN_ACCESS_ACTION_GET_CREDENTIALS,
		r,
		ctx,
		max_timeout_seconds,
	)
}
