name: Build and Push Daemon

on:
  push:
    branches:
      - "dev-docker"
      - "deploy/dev"
  pull_request:
    branches:
      - "dev-docker"
  release:
    types: [published]

concurrency:
  group: build-push-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  BOSS_DAEMON_IMAGE_NAME: ${{ vars.BOSS_DAEMON_IMAGE_NAME || format('ghcr.io/{0}', github.repository) }}

jobs:
  matrix_prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set matrix
        id: set-matrix
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "matrix={\"include\":[
              {\"service_name\":\"build-serverless-daemon-amd64\",\"image_name_env\":\"BOSS_DAEMON_IMAGE_NAME\",\"platform\":\"linux/amd64\",\"scope\":\"serverless\"},
              {\"service_name\":\"build-local-daemon-amd64\",\"image_name_env\":\"BOSS_DAEMON_IMAGE_NAME\",\"platform\":\"linux/amd64\",\"scope\":\"local\"}
            ]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"include\":[
              {\"service_name\":\"build-serverless-daemon-amd64\",\"image_name_env\":\"BOSS_DAEMON_IMAGE_NAME\",\"platform\":\"linux/amd64\",\"scope\":\"serverless\"},
              {\"service_name\":\"build-serverless-daemon-arm64\",\"image_name_env\":\"BOSS_DAEMON_IMAGE_NAME\",\"platform\":\"linux/arm64\",\"scope\":\"serverless\"},
              {\"service_name\":\"build-local-daemon-amd64\",\"image_name_env\":\"BOSS_DAEMON_IMAGE_NAME\",\"platform\":\"linux/amd64\",\"scope\":\"local\"},
              {\"service_name\":\"build-local-daemon-arm64\",\"image_name_env\":\"BOSS_DAEMON_IMAGE_NAME\",\"platform\":\"linux/arm64\",\"scope\":\"local\"}
            ]}" >> $GITHUB_OUTPUT

  build:
    needs: matrix_prepare
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'arm64_runner' || 'ubuntu-latest' }}
    strategy:
      matrix: ${{ fromJson(needs.matrix_prepare.outputs.matrix) }}

    defaults:
      run:
        working-directory: boss-plugin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BOSS_DAEMON_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=branch
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            type=raw,value=${{ github.ref_name }},enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build Docker Image
        run: |
          docker build --build-arg PLATFORM=${{ matrix.scope }} --build-arg VERSION=${{ github.sha }} \
            -t boss-plugin-daemon -f ./docker/${{ matrix.scope }}.dockerfile .

      - name: Tag Docker Images
        if: github.event_name != 'pull_request'
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'); do
            docker tag boss-plugin-daemon "${{ env.BOSS_DAEMON_IMAGE_NAME }}:$tag-${{ matrix.scope }}-${{ env.PLATFORM_PAIR }}"
          done

      - name: Push Docker Images
        if: github.event_name != 'pull_request'
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'); do
            docker push "${{ env.BOSS_DAEMON_IMAGE_NAME }}:$tag-${{ matrix.scope }}-${{ env.PLATFORM_PAIR }}"
          done

  create-manifest:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scope: [serverless, local]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BOSS_DAEMON_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=branch
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            type=raw,value=${{ github.ref_name }},enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Create and Push Multi-Arch Manifest
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'); do
            docker manifest create "${{ env.BOSS_DAEMON_IMAGE_NAME }}:$tag-${{ matrix.scope }}" \
              "${{ env.BOSS_DAEMON_IMAGE_NAME }}:$tag-${{ matrix.scope }}-linux-amd64" \
              "${{ env.BOSS_DAEMON_IMAGE_NAME }}:$tag-${{ matrix.scope }}-linux-arm64"

            docker manifest push "${{ env.BOSS_DAEMON_IMAGE_NAME }}:$tag-${{ matrix.scope }}"
          done
